# CategoricalLike CategorizedOnly Model Prediction Preparation

CategoricalLike CategorizedOnly Model Table will be prepared for use in Prediction Notebook

This table will be used for supply extra information about recommendation

In [1]:
#Importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import warnings

In [2]:
#Printing library versions
print('numpy Version: ' + np.__version__)
print('pandas Version: ' + pd.__version__)
print('tensorflow Version: ' + tf.__version__)

numpy Version: 1.16.5
pandas Version: 0.25.1
tensorflow Version: 2.0.0


In [3]:
#GPU will be used for Prediction and Evaluation
myGPU = tf.test.gpu_device_name()
if myGPU:
    print(myGPU)
else:
    print("Error")

/device:GPU:0


In [4]:
#Reading Qualified CategoricalLike CategorizedOnly training data from pkl file
trainingDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/CategorizedOnly/Training.pkl")
trainingDf

UserId  MovieId  Category
0         9999      690         1
1         4532     1007         2
2         3969      726         2
3         1271     9157         1
4         7932     1201         1
...        ...      ...       ...
753628    9556     1403         1
753629    4795    17453         1
753630    2116      434         1
753631    1910     4512         1
753632    6015      110         2

[753633 rows x 3 columns]

In [5]:
#creating a user array for training input 
trainingUser = trainingDf[['UserId']].values.astype(np.int32)
trainingUser = trainingUser.reshape((trainingUser.shape[0]))
trainingUser

array([9999, 4532, 3969, ..., 2116, 1910, 6015])

In [6]:
#creating a movie array for training input 
trainingMovie = trainingDf[['MovieId']].values.astype(np.int32)
trainingMovie = trainingMovie.reshape((trainingMovie.shape[0]))
trainingMovie

array([ 690, 1007,  726, ...,  434, 4512,  110])

In [7]:
#creating an array for training input 
trainingX = [trainingUser, trainingMovie]
trainingX

[array([9999, 4532, 3969, ..., 2116, 1910, 6015]),
 array([ 690, 1007,  726, ...,  434, 4512,  110])]

In [8]:
#Output is converted to One-Hot Encoding and creating an array for training output 
trainingY = []
for i in trainingDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    trainingY.append(current)
trainingY = np.array(trainingY).astype(np.int8)
trainingY

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [9]:
#Reading Qualified CategoricalLike CategorizedOnly validation data from pkl file
validationDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/CategorizedOnly/Validation.pkl")
validationDf

UserId  MovieId  Category
0          238      315         1
1         2311      933         1
2         9877      866         2
3          234      424         2
4         8066     1669         2
...        ...      ...       ...
123625    2038      280         1
123626    8717      154         2
123627    7348     1068         1
123628    1932    12061         1
123629    7604      303         1

[123630 rows x 3 columns]

In [10]:
#creating a user array for validation input 
validationUser = validationDf[['UserId']].values.astype(np.int32)
validationUser = validationUser.reshape((validationUser.shape[0]))
validationUser

array([ 238, 2311, 9877, ..., 7348, 1932, 7604])

In [11]:
#creating a movie array for validation input 
validationMovie = validationDf[['MovieId']].values.astype(np.int32)
validationMovie = validationMovie.reshape((validationMovie.shape[0]))
validationMovie

array([  315,   933,   866, ...,  1068, 12061,   303])

In [12]:
#creating an array for validation input 
validationX = [validationUser, validationMovie]
validationX

[array([ 238, 2311, 9877, ..., 7348, 1932, 7604]),
 array([  315,   933,   866, ...,  1068, 12061,   303])]

In [13]:
#Output is converted to One-Hot Encoding and creating an array for validation output 
validationY = []
for i in validationDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    validationY.append(current)
validationY = np.array(validationY).astype(np.int8)
validationY

array([[0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=int8)

In [14]:
#Reading Qualified CategoricalLike CategorizedOnly test data from pkl file
testDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/CategorizedOnly/Test.pkl")
testDf

UserId  MovieId  Category
0         1470      861         2
1         2736      789         2
2         8041     1101         2
3         3317      336         1
4         5490     2359         1
...        ...      ...       ...
123625    3246      983         1
123626    8886     2413         2
123627    1487      776         0
123628    7680       97         1
123629    9080     4385         2

[123630 rows x 3 columns]

In [15]:
#creating a user array for test input 
testUser = testDf[['UserId']].values.astype(np.int32)
testUser = testUser.reshape((testUser.shape[0]))
testUser

array([1470, 2736, 8041, ..., 1487, 7680, 9080])

In [16]:
#creating a movie array for test input 
testMovie = testDf[['MovieId']].values.astype(np.int32)
testMovie = testMovie.reshape((testMovie.shape[0]))
testMovie

array([ 861,  789, 1101, ...,  776,   97, 4385])

In [17]:
#creating an array for test input 
testX = [testUser, testMovie]
testX

[array([1470, 2736, 8041, ..., 1487, 7680, 9080]),
 array([ 861,  789, 1101, ...,  776,   97, 4385])]

In [18]:
#Output is converted to One-Hot Encoding and creating an array for test output 
testY = []
for i in testDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    testY.append(current)
testY = np.array(testY).astype(np.int8)
testY

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [19]:
#ignore warnings due to Converting sparse IndexedSlices to a dense Tensor of unknown shape warning
warnings.filterwarnings('ignore')

#Best Model For CategoricalLike CategorizedOnly dataset loading from h5 file
#See Training5 notebook for more information
model = tf.keras.models.load_model("../Model/CategorizedOnlyModel/Model18.h5")

In [20]:
#Best Model evaluating with training values
with tf.device('/GPU:0'):
    trainingResult = model.evaluate(x = trainingX, y = trainingY, batch_size = 64, verbose = 0)

In [21]:
#Print trainingResult
trainingResult

[0.6391065250865303, 0.8177135]

In [22]:
#Best Model evaluating with validation values
with tf.device('/GPU:0'):
    validationResult = model.evaluate(x = validationX, y = validationY, batch_size = 64, verbose = 0)

In [23]:
#Print validationResult
validationResult

[0.7514301483351311, 0.78019893]

In [24]:
#Best Model evaluating with test values
with tf.device('/GPU:0'):
    testResult = model.evaluate(x = testX, y = testY, batch_size = 64, verbose = 0)

In [25]:
#Print testResult
testResult

[0.7505836447224613, 0.78219926]

In [26]:
#Creating DataFrame for data and model metrics
modelDf = pd.DataFrame(data = {'ModelData': pd.Series(['Training', 'Validation', 'Test'], dtype='str'),
                               'Hated' : pd.Series([trainingDf[trainingDf['Category'] == 0].shape[0], validationDf[validationDf['Category'] == 0].shape[0], testDf[testDf['Category'] == 0].shape[0]], dtype='int'),
                               'Not Liked' : pd.Series([trainingDf[trainingDf['Category'] == 1].shape[0], validationDf[validationDf['Category'] == 1].shape[0], testDf[testDf['Category'] == 1].shape[0]], dtype='int'),
                               'Liked' : pd.Series([trainingDf[trainingDf['Category'] == 2].shape[0], validationDf[validationDf['Category'] == 2].shape[0], testDf[testDf['Category'] == 2].shape[0]], dtype='int'),
                               'Loss': pd.Series([trainingResult[0], validationResult[0], testResult[0]], dtype='float'),
                               'Accuracy': pd.Series([trainingResult[1], validationResult[1], testResult[1]], dtype='float')})
modelDf

ModelData  Hated  Not Liked   Liked      Loss  Accuracy
0    Training  50014     329878  373741  0.639107  0.817713
1  Validation   7834      54101   61695  0.751430  0.780199
2        Test   7860      53972   61798  0.750584  0.782199

In [27]:
#Saving modeldf and Clearing memory
modelDf.to_pickle("../PredictData/ModelTable/CategorizedOnly.pkl")
del modelDf

In [28]:
#Best Model predicting training Category
with tf.device('/GPU:0'):
    predictTraining = model.predict(x = trainingX)
predictTraining

array([[3.7304617e-02, 8.7954044e-01, 8.3154961e-02],
       [8.5988596e-08, 1.2510450e-03, 9.9874890e-01],
       [1.0525373e-02, 4.4061917e-01, 5.4885548e-01],
       ...,
       [1.8831097e-02, 8.6559427e-01, 1.1557468e-01],
       [3.0967642e-02, 4.1549009e-01, 5.5354220e-01],
       [3.0620794e-03, 1.7200874e-01, 8.2492924e-01]], dtype=float32)

In [29]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending trainingDf as predicted category
trainingDf['CategoryPredict'] = predictTraining.argmax(axis=1)
trainingDf

UserId  MovieId  Category  CategoryPredict
0         9999      690         1                1
1         4532     1007         2                2
2         3969      726         2                2
3         1271     9157         1                1
4         7932     1201         1                1
...        ...      ...       ...              ...
753628    9556     1403         1                2
753629    4795    17453         1                1
753630    2116      434         1                1
753631    1910     4512         1                2
753632    6015      110         2                2

[753633 rows x 4 columns]

In [30]:
#Best Model predicting validation Likes
with tf.device('/GPU:0'):
    predictValidation = model.predict(x = validationX)
predictValidation

array([[0.07097384, 0.9037039 , 0.02532224],
       [0.00752375, 0.2642689 , 0.72820735],
       [0.04796013, 0.5204251 , 0.43161476],
       ...,
       [0.05751302, 0.69621956, 0.2462674 ],
       [0.0423302 , 0.7966883 , 0.16098148],
       [0.08346274, 0.7001545 , 0.2163828 ]], dtype=float32)

In [31]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending validationDf as predicted category
validationDf['CategoryPredict'] = predictValidation.argmax(axis=1)
validationDf

UserId  MovieId  Category  CategoryPredict
0          238      315         1                1
1         2311      933         1                2
2         9877      866         2                1
3          234      424         2                2
4         8066     1669         2                2
...        ...      ...       ...              ...
123625    2038      280         1                1
123626    8717      154         2                2
123627    7348     1068         1                1
123628    1932    12061         1                1
123629    7604      303         1                1

[123630 rows x 4 columns]

In [32]:
#Best Model predicting test Likes
with tf.device('/GPU:0'):
    predictTest = model.predict(x = testX)
predictTest

array([[0.03838974, 0.47397098, 0.48763934],
       [0.01451858, 0.34787998, 0.63760144],
       [0.00528734, 0.20712379, 0.7875889 ],
       ...,
       [0.10777438, 0.8459385 , 0.04628707],
       [0.45332143, 0.5036544 , 0.04302417],
       [0.00789097, 0.39689678, 0.5952123 ]], dtype=float32)

In [33]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending testDf as predicted category
testDf['CategoryPredict'] = predictTest.argmax(axis=1)
testDf

UserId  MovieId  Category  CategoryPredict
0         1470      861         2                2
1         2736      789         2                2
2         8041     1101         2                2
3         3317      336         1                2
4         5490     2359         1                2
...        ...      ...       ...              ...
123625    3246      983         1                1
123626    8886     2413         2                2
123627    1487      776         0                1
123628    7680       97         1                1
123629    9080     4385         2                2

[123630 rows x 4 columns]

In [34]:
#Dataframes merging
allDataFrame = pd.concat([trainingDf, validationDf, testDf]).reset_index(drop=True)
allDataFrame

UserId  MovieId  Category  CategoryPredict
0          9999      690         1                1
1          4532     1007         2                2
2          3969      726         2                2
3          1271     9157         1                1
4          7932     1201         1                1
...         ...      ...       ...              ...
1000888    3246      983         1                1
1000889    8886     2413         2                2
1000890    1487      776         0                1
1000891    7680       97         1                1
1000892    9080     4385         2                2

[1000893 rows x 4 columns]

In [35]:
#Getting all unique UserId from allDataFrame and create new Data Frame from this values
#This Data frame will used as lookup table for prediction script
userRange = range(allDataFrame['UserId'].unique().shape[0])
lookupTable = pd.DataFrame(data = {'User' : userRange})
lookupTable

User
0          0
1          1
2          2
3          3
4          4
...      ...
10068  10068
10069  10069
10070  10070
10071  10071
10072  10072

[10073 rows x 1 columns]

In [36]:
#Defined function will be checked if prediction is true
def CorrectPrediction(category, prediction):
    result = 0
    for i in range(len(category)):
        if category[i] == prediction[i]:
            result += 1
    return result

In [37]:
#Calculations for each user
calculations = np.empty(shape = (8, lookupTable.shape[0]))
for i in userRange:
    
    #Training dataframe calculations
    queryFrame = trainingDf[trainingDf['UserId'] == i]
    calculations[0][i] = queryFrame.shape[0]
    calculations[1][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)

        
    #Validaiton dataframe calculations
    queryFrame = validationDf[validationDf['UserId'] == i]
    calculations[2][i] = queryFrame.shape[0]
    calculations[3][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)
    
    #Test dataframe calculations
    queryFrame = testDf[testDf['UserId'] == i]
    calculations[4][i] = queryFrame.shape[0]
    calculations[5][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)

    
    #All dataframe calculations
    #Since All dataframe contains training, validation and test dataframes
    #All dataframe results can be calculated by simply summing the training, validation and test results
    calculations[6][i] = calculations[0][i] + calculations[2][i] + calculations[4][i]
    calculations[7][i] = calculations[1][i] + calculations[3][i] + calculations[5][i]


#print
calculations

array([[ 12.,   8.,   6., ...,  24.,  30., 731.],
       [  7.,   5.,   6., ...,  21.,  21., 624.],
       [  1.,   5.,   3., ...,   5.,   6., 120.],
       ...,
       [  0.,   1.,   2., ...,   4.,   5., 103.],
       [ 16.,  15.,  11., ...,  34.,  42., 972.],
       [  7.,   8.,   9., ...,  30.,  30., 829.]])

In [38]:
#Calculations adding lookup table

#Training data representation count
lookupTable['TraingingRep'] = calculations[0].astype(np.int32)
#Training data Correct Predictions
lookupTable['TrainingCorrect'] = calculations[1].astype(np.int32)

#Validation data representation count
lookupTable['ValidationRep'] = calculations[2].astype(np.int32)
#validation data Correct Predictions
lookupTable['ValidationCorrect'] = calculations[3].astype(np.int32)

#Test data representation count
lookupTable['TestRep'] = calculations[4].astype(np.int32)
#test data Correct Predictions
lookupTable['TestCorrect'] = calculations[5].astype(np.int32)

#All data representation count
lookupTable['AllRep'] = calculations[6].astype(np.int32)
#all data Correct Predictions
lookupTable['AllCorrect'] = calculations[7].astype(np.int32)

lookupTable

User  TraingingRep  TrainingCorrect  ValidationRep  ValidationCorrect  \
0          0            12                7              1                  0   
1          1             8                5              5                  2   
2          2             6                6              3                  1   
3          3           554              393            103                 62   
4          4            56               51              8                  8   
...      ...           ...              ...            ...                ...   
10068  10068            12                9              4                  1   
10069  10069            21               16              1                  0   
10070  10070            24               21              5                  5   
10071  10071            30               21              6                  4   
10072  10072           731              624            120                102   

       TestRep  TestCorrect  AllRep  AllCorrect  
0            3            0      16           7  
1            2            1      15           8  
2            2            2      11           9  
3           79           56     736         511  
4            8            7      72          66  
...        ...          ...     ...         ...  
10068        2            1      18          11  
10069        2            2      24          18  
10070        5            4      34          30  
10071        6            5      42          30  
10072      121          103     972         829  

[10073 rows x 9 columns]

In [39]:
#Lookup table save as pkl file
lookupTable.to_pickle("../PredictData/LookupTable/CategorizedOnly.pkl")
del calculations
del trainingDf
del validationDf
del testDf
del allDataFrame
del lookupTable