# CategoricalLike NotCategorizedSample Model Prediction Preparation

CategoricalLike NotCategorizedSample Model Table will be prepared for use in Prediction Notebook

This table will be used for supply extra information about recommendation

In [1]:
#Importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import warnings

In [2]:
#Printing library versions
print('numpy Version: ' + np.__version__)
print('pandas Version: ' + pd.__version__)
print('tensorflow Version: ' + tf.__version__)

numpy Version: 1.16.5
pandas Version: 0.25.1
tensorflow Version: 2.0.0


In [3]:
#GPU will be used for Prediction and Evaluation
myGPU = tf.test.gpu_device_name()
if myGPU:
    print(myGPU)
else:
    print("Error")

/device:GPU:0


In [4]:
#Reading Qualified CategoricalLike NotCategorizedSample training data from pkl file
trainingDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/NotCategorizedSample/Training.pkl")
trainingDf

UserId  MovieId  Category
0         2628      195         2
1         4474      565         2
2         5175     9476         2
3         9268     1308         2
4         9210      117         2
...        ...      ...       ...
760794    3289     1326         2
760795    4730      309         1
760796    3821    15052         2
760797    6935      174         1
760798    2019    12688         0

[760799 rows x 3 columns]

In [5]:
#creating a user array for training input 
trainingUser = trainingDf[['UserId']].values.astype(np.int32)
trainingUser = trainingUser.reshape((trainingUser.shape[0]))
trainingUser

array([2628, 4474, 5175, ..., 3821, 6935, 2019])

In [6]:
#creating a movie array for training input 
trainingMovie = trainingDf[['MovieId']].values.astype(np.int32)
trainingMovie = trainingMovie.reshape((trainingMovie.shape[0]))
trainingMovie

array([  195,   565,  9476, ..., 15052,   174, 12688])

In [7]:
#creating an array for training input 
trainingX = [trainingUser, trainingMovie]
trainingX

[array([2628, 4474, 5175, ..., 3821, 6935, 2019]),
 array([  195,   565,  9476, ..., 15052,   174, 12688])]

In [8]:
#Output is converted to One-Hot Encoding and creating an array for training output 
trainingY = []
for i in trainingDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    trainingY.append(current)
trainingY = np.array(trainingY).astype(np.int8)
trainingY

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

In [9]:
#Reading Qualified CategoricalLike NotCategorizedSample validation data from pkl file
validationDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/NotCategorizedSample/Validation.pkl")
validationDf

UserId  MovieId  Category
0         7160     1089         2
1         3734      466         2
2         8077      315         1
3         8888     5353         1
4         7588      382         1
...        ...      ...       ...
125046    5175     2366         1
125047    4289      246         2
125048    9167     4305         1
125049     490     1128         1
125050    3711      922         2

[125051 rows x 3 columns]

In [10]:
#creating a user array for validation input 
validationUser = validationDf[['UserId']].values.astype(np.int32)
validationUser = validationUser.reshape((validationUser.shape[0]))
validationUser

array([7160, 3734, 8077, ..., 9167,  490, 3711])

In [11]:
#creating a movie array for validation input 
validationMovie = validationDf[['MovieId']].values.astype(np.int32)
validationMovie = validationMovie.reshape((validationMovie.shape[0]))
validationMovie

array([1089,  466,  315, ..., 4305, 1128,  922])

In [12]:
#creating an array for validation input 
validationX = [validationUser, validationMovie]
validationX

[array([7160, 3734, 8077, ..., 9167,  490, 3711]),
 array([1089,  466,  315, ..., 4305, 1128,  922])]

In [13]:
#Output is converted to One-Hot Encoding and creating an array for validation output 
validationY = []
for i in validationDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    validationY.append(current)
validationY = np.array(validationY).astype(np.int8)
validationY

array([[0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [14]:
#Reading Qualified CategoricalLike NotCategorizedSample test data from pkl file
testDf = pd.read_pickle("../Data/pkl/1M/Qualified/CategoricalLike/NotCategorizedSample/Test.pkl")
testDf

UserId  MovieId  Category
0         2462     2321         1
1         6121     2859         1
2         6835     2574         0
3         4628     1167         1
4         8252     2558         1
...        ...      ...       ...
125046     221     1027         1
125047    7845       75         1
125048    8340     1370         2
125049   10072      344         1
125050    2149     5635         1

[125051 rows x 3 columns]

In [15]:
#creating a user array for test input 
testUser = testDf[['UserId']].values.astype(np.int32)
testUser = testUser.reshape((testUser.shape[0]))
testUser

array([ 2462,  6121,  6835, ...,  8340, 10072,  2149])

In [16]:
#creating a movie array for test input 
testMovie = testDf[['MovieId']].values.astype(np.int32)
testMovie = testMovie.reshape((testMovie.shape[0]))
testMovie

array([2321, 2859, 2574, ..., 1370,  344, 5635])

In [17]:
#creating an array for test input 
testX = [testUser, testMovie]
testX

[array([ 2462,  6121,  6835, ...,  8340, 10072,  2149]),
 array([2321, 2859, 2574, ..., 1370,  344, 5635])]

In [18]:
#Output is converted to One-Hot Encoding and creating an array for test output 
testY = []
for i in testDf[['Category']].values:
    current = np.zeros(3)
    current[i] = 1
    testY.append(current)
testY = np.array(testY).astype(np.int8)
testY

array([[0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]], dtype=int8)

In [19]:
#ignore warnings due to Converting sparse IndexedSlices to a dense Tensor of unknown shape warning
warnings.filterwarnings('ignore')

#Best Model For CategoricalLike NotCategorizedSample dataset loading from h5 file
#See Training6 notebook for more information
model = tf.keras.models.load_model("../Model/NotCategorizedSampleModel/Model18.h5")

In [20]:
#Best Model evaluating with training values
with tf.device('/GPU:0'):
    trainingResult = model.evaluate(x = trainingX, y = trainingY, batch_size = 64, verbose = 0)

In [21]:
#Print trainingResult
trainingResult

[0.6631638511593201, 0.81725353]

In [22]:
#Best Model evaluating with validation values
with tf.device('/GPU:0'):
    validationResult = model.evaluate(x = validationX, y = validationY, batch_size = 64, verbose = 0)

In [23]:
#Print validationResult
validationResult

[0.7951336762613244, 0.77715254]

In [24]:
#Best Model evaluating with test values
with tf.device('/GPU:0'):
    testResult = model.evaluate(x = testX, y = testY, batch_size = 64, verbose = 0)

In [25]:
#Print testResult
testResult

[0.7944960329917007, 0.77834356]

In [26]:
#Creating DataFrame for data and model metrics
modelDf = pd.DataFrame(data = {'ModelData': pd.Series(['Training', 'Validation', 'Test'], dtype='str'),
                               'Hated' : pd.Series([trainingDf[trainingDf['Category'] == 0].shape[0], validationDf[validationDf['Category'] == 0].shape[0], testDf[testDf['Category'] == 0].shape[0]], dtype='int'),
                               'Liked' : pd.Series([trainingDf[trainingDf['Category'] == 1].shape[0], validationDf[validationDf['Category'] == 1].shape[0], testDf[testDf['Category'] == 1].shape[0]], dtype='int'),
                               'Loved' : pd.Series([trainingDf[trainingDf['Category'] == 2].shape[0], validationDf[validationDf['Category'] == 2].shape[0], testDf[testDf['Category'] == 2].shape[0]], dtype='int'),
                               'Loss': pd.Series([trainingResult[0], validationResult[0], testResult[0]], dtype='float'),
                               'Accuracy': pd.Series([trainingResult[1], validationResult[1], testResult[1]], dtype='float')})
modelDf

ModelData  Hated   Liked   Loved      Loss  Accuracy
0    Training  57452  329602  373745  0.663164  0.817254
1  Validation   9153   54141   61757  0.795134  0.777153
2        Test   9111   54208   61732  0.794496  0.778344

In [27]:
#Saving modeldf and Clearing memory
modelDf.to_pickle("../PredictData/ModelTable/NotCategorizedSample.pkl")
del modelDf

In [28]:
#Best Model predicting training Category
with tf.device('/GPU:0'):
    predictTraining = model.predict(x = trainingX)
predictTraining

array([[3.8028518e-03, 3.6197764e-01, 6.3421947e-01],
       [5.3948504e-03, 2.5466153e-01, 7.3994362e-01],
       [4.0125507e-03, 6.7373788e-01, 3.2224953e-01],
       ...,
       [7.4677635e-05, 1.1931168e-01, 8.8061368e-01],
       [1.6378029e-01, 6.8841082e-01, 1.4780881e-01],
       [4.0645683e-01, 5.2676743e-01, 6.6775709e-02]], dtype=float32)

In [29]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending trainingDf as predicted category
trainingDf['CategoryPredict'] = predictTraining.argmax(axis=1)
trainingDf

UserId  MovieId  Category  CategoryPredict
0         2628      195         2                2
1         4474      565         2                2
2         5175     9476         2                1
3         9268     1308         2                2
4         9210      117         2                1
...        ...      ...       ...              ...
760794    3289     1326         2                2
760795    4730      309         1                1
760796    3821    15052         2                2
760797    6935      174         1                1
760798    2019    12688         0                1

[760799 rows x 4 columns]

In [30]:
#Best Model predicting validation Likes
with tf.device('/GPU:0'):
    predictValidation = model.predict(x = validationX)
predictValidation

array([[2.5534126e-04, 5.5255566e-02, 9.4448906e-01],
       [9.5287914e-04, 1.1299457e-01, 8.8605261e-01],
       [1.5821962e-02, 4.8494801e-01, 4.9923003e-01],
       ...,
       [2.3499599e-02, 2.8833607e-01, 6.8816435e-01],
       [1.4898194e-02, 3.2478151e-01, 6.6032034e-01],
       [1.4671355e-02, 2.9999170e-01, 6.8533695e-01]], dtype=float32)

In [31]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending validationDf as predicted category
validationDf['CategoryPredict'] = predictValidation.argmax(axis=1)
validationDf

UserId  MovieId  Category  CategoryPredict
0         7160     1089         2                2
1         3734      466         2                2
2         8077      315         1                2
3         8888     5353         1                1
4         7588      382         1                1
...        ...      ...       ...              ...
125046    5175     2366         1                1
125047    4289      246         2                2
125048    9167     4305         1                2
125049     490     1128         1                2
125050    3711      922         2                2

[125051 rows x 4 columns]

In [32]:
#Best Model predicting test Likes
with tf.device('/GPU:0'):
    predictTest = model.predict(x = testX)
predictTest

array([[0.07686207, 0.58647054, 0.3366674 ],
       [0.00833827, 0.7907909 , 0.20087087],
       [0.20370923, 0.7592763 , 0.03701449],
       ...,
       [0.00185385, 0.26134047, 0.7368057 ],
       [0.0140478 , 0.70455635, 0.28139585],
       [0.00339339, 0.61670303, 0.37990355]], dtype=float32)

In [33]:
#Since model is categorical model prediction returns inclusion rate for each category (Fuzzy Logic)
#see https://en.wikipedia.org/wiki/Fuzzy_logic
#Index of maximum predicted rate is appending testDf as predicted category
testDf['CategoryPredict'] = predictTest.argmax(axis=1)
testDf

UserId  MovieId  Category  CategoryPredict
0         2462     2321         1                1
1         6121     2859         1                1
2         6835     2574         0                1
3         4628     1167         1                1
4         8252     2558         1                2
...        ...      ...       ...              ...
125046     221     1027         1                2
125047    7845       75         1                1
125048    8340     1370         2                2
125049   10072      344         1                1
125050    2149     5635         1                1

[125051 rows x 4 columns]

In [34]:
#Dataframes merging
allDataFrame = pd.concat([trainingDf, validationDf, testDf]).reset_index(drop=True)
allDataFrame

UserId  MovieId  Category  CategoryPredict
0          2628      195         2                2
1          4474      565         2                2
2          5175     9476         2                1
3          9268     1308         2                2
4          9210      117         2                1
...         ...      ...       ...              ...
1010896     221     1027         1                2
1010897    7845       75         1                1
1010898    8340     1370         2                2
1010899   10072      344         1                1
1010900    2149     5635         1                1

[1010901 rows x 4 columns]

In [35]:
#Getting all unique UserId from allDataFrame and create new Data Frame from this values
#This Data frame will used as lookup table for prediction script
userRange = range(allDataFrame['UserId'].unique().shape[0])
lookupTable = pd.DataFrame(data = {'User' : userRange})
lookupTable

User
0          0
1          1
2          2
3          3
4          4
...      ...
10068  10068
10069  10069
10070  10070
10071  10071
10072  10072

[10073 rows x 1 columns]

In [36]:
#Defined function will be checked if prediction is true
def CorrectPrediction(category, prediction):
    result = 0
    for i in range(len(category)):
        if category[i] == prediction[i]:
            result += 1
    return result

In [37]:
#Calculations for each user
calculations = np.empty(shape = (8, lookupTable.shape[0]))
for i in userRange:
    
    #Training dataframe calculations
    queryFrame = trainingDf[trainingDf['UserId'] == i]
    calculations[0][i] = queryFrame.shape[0]
    calculations[1][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)

        
    #Validaiton dataframe calculations
    queryFrame = validationDf[validationDf['UserId'] == i]
    calculations[2][i] = queryFrame.shape[0]
    calculations[3][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)
    
    #Test dataframe calculations
    queryFrame = testDf[testDf['UserId'] == i]
    calculations[4][i] = queryFrame.shape[0]
    calculations[5][i] = CorrectPrediction(queryFrame['Category'].values, queryFrame['CategoryPredict'].values)

    
    #All dataframe calculations
    #Since All dataframe contains training, validation and test dataframes
    #All dataframe results can be calculated by simply summing the training, validation and test results
    calculations[6][i] = calculations[0][i] + calculations[2][i] + calculations[4][i]
    calculations[7][i] = calculations[1][i] + calculations[3][i] + calculations[5][i]


#print
calculations

array([[ 12.,  16.,   7., ...,  27.,  33., 729.],
       [  9.,   8.,   6., ...,  23.,  21., 610.],
       [  3.,   0.,   4., ...,   5.,   5., 116.],
       ...,
       [  1.,   1.,   0., ...,   4.,   3., 109.],
       [ 17.,  17.,  13., ...,  36.,  43., 973.],
       [ 13.,   9.,  10., ...,  31.,  28., 818.]])

In [38]:
#Calculations adding lookup table

#Training data representation count
lookupTable['TraingingRep'] = calculations[0].astype(np.int32)
#Training data Correct Predictions
lookupTable['TrainingCorrect'] = calculations[1].astype(np.int32)

#Validation data representation count
lookupTable['ValidationRep'] = calculations[2].astype(np.int32)
#validation data Correct Predictions
lookupTable['ValidationCorrect'] = calculations[3].astype(np.int32)

#Test data representation count
lookupTable['TestRep'] = calculations[4].astype(np.int32)
#test data Correct Predictions
lookupTable['TestCorrect'] = calculations[5].astype(np.int32)

#All data representation count
lookupTable['AllRep'] = calculations[6].astype(np.int32)
#all data Correct Predictions
lookupTable['AllCorrect'] = calculations[7].astype(np.int32)

lookupTable

User  TraingingRep  TrainingCorrect  ValidationRep  ValidationCorrect  \
0          0            12                9              3                  3   
1          1            16                8              0                  0   
2          2             7                6              4                  4   
3          3           565              419             85                 51   
4          4            51               45             11                 10   
...      ...           ...              ...            ...                ...   
10068  10068            16               12              2                  0   
10069  10069            19               16              2                  2   
10070  10070            27               23              5                  4   
10071  10071            33               21              5                  4   
10072  10072           729              610            116                 99   

       TestRep  TestCorrect  AllRep  AllCorrect  
0            2            1      17          13  
1            1            1      17           9  
2            2            0      13          10  
3           87           54     737         524  
4           11           10      73          65  
...        ...          ...     ...         ...  
10068        3            0      21          12  
10069        3            1      24          19  
10070        4            4      36          31  
10071        5            3      43          28  
10072      128          109     973         818  

[10073 rows x 9 columns]

In [39]:
#Lookup table save as pkl file
lookupTable.to_pickle("../PredictData/LookupTable/NotCategorizedSample.pkl")
del calculations
del trainingDf
del validationDf
del testDf
del allDataFrame
del lookupTable