# BinaryInteraction NotInteractedSample Model Prediction Preparation

BinaryInteraction NotInteractedSample Model Table will be prepared for use in Prediction Notebook

This table will be used for supply extra information about recommendation

In [1]:
#Importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import warnings

In [2]:
#Printing library versions
print('numpy Version: ' + np.__version__)
print('pandas Version: ' + pd.__version__)
print('tensorflow Version: ' + tf.__version__)

numpy Version: 1.16.5
pandas Version: 0.25.1
tensorflow Version: 2.0.0


In [3]:
#GPU will be used for Prediction and Evaluation
myGPU = tf.test.gpu_device_name()
if myGPU:
    print(myGPU)
else:
    print("Error")

/device:GPU:0


In [4]:
#Reading Qualified BinaryInteraction NotInteractedSample training data from pkl file
trainingDf = pd.read_pickle("../Data/pkl/1M/Qualified/BinaryInteraction/NotInteractedSample/Training.pkl")
trainingDf

UserId  MovieId  Interaction
0          5282      244            1
1           766      213            1
2          8209     1198            1
3          1067     1828            1
4          6915     1256            1
...         ...      ...          ...
1001131   10072     1095            1
1001132     133      396            1
1001133    8852     6102            1
1001134    5174     4218            0
1001135    2711     3209            1

[1001136 rows x 3 columns]

In [5]:
#creating a user array for training input 
trainingUser = trainingDf[['UserId']].values.astype(np.int32)
trainingUser = trainingUser.reshape((trainingUser.shape[0]))
trainingUser

array([5282,  766, 8209, ..., 8852, 5174, 2711])

In [6]:
#creating a movie array for training input 
trainingMovie = trainingDf[['MovieId']].values.astype(np.int32)
trainingMovie = trainingMovie.reshape((trainingMovie.shape[0]))
trainingMovie

array([ 244,  213, 1198, ..., 6102, 4218, 3209])

In [7]:
#creating an array for training input 
trainingX = [trainingUser, trainingMovie]
trainingX

[array([5282,  766, 8209, ..., 8852, 5174, 2711]),
 array([ 244,  213, 1198, ..., 6102, 4218, 3209])]

In [8]:
#creating an array for training output 
trainingY = trainingDf[['Interaction']].values.astype(np.int8)
trainingY = trainingY.reshape((trainingY.shape[0]))
trainingY

array([1, 1, 1, ..., 1, 0, 1], dtype=int8)

In [9]:
#Reading Qualified BinaryInteraction NotInteractedSample validation data from pkl file
validationDf = pd.read_pickle("../Data/pkl/1M/Qualified/BinaryInteraction/NotInteractedSample/Validation.pkl")
validationDf

UserId  MovieId  Interaction
0         8455      142            1
1         1945      530            1
2         7588     4030            1
3         6186     3563            1
4         1088     8835            1
...        ...      ...          ...
166689    8048     1278            1
166690    5234     4508            0
166691    9471    19733            0
166692    8078    15906            0
166693    5809      337            1

[166694 rows x 3 columns]

In [10]:
#creating a user array for validation input 
validationUser = validationDf[['UserId']].values.astype(np.int32)
validationUser = validationUser.reshape((validationUser.shape[0]))
validationUser

array([8455, 1945, 7588, ..., 9471, 8078, 5809])

In [11]:
#creating a movie array for validation input 
validationMovie = validationDf[['MovieId']].values.astype(np.int32)
validationMovie = validationMovie.reshape((validationMovie.shape[0]))
validationMovie

array([  142,   530,  4030, ..., 19733, 15906,   337])

In [12]:
#creating an array for validation input 
validationX = [validationUser, validationMovie]
validationX

[array([8455, 1945, 7588, ..., 9471, 8078, 5809]),
 array([  142,   530,  4030, ..., 19733, 15906,   337])]

In [13]:
#creating an array for validation output 
validationY = validationDf[['Interaction']].values.astype(np.int8)
validationY = validationY.reshape((validationY.shape[0]))
validationY

array([1, 1, 1, ..., 0, 0, 1], dtype=int8)

In [14]:
#Reading Qualified BinaryInteraction NotInteractedSample test data from pkl file
testDf = pd.read_pickle("../Data/pkl/1M/Qualified/BinaryInteraction/NotInteractedSample/Test.pkl")
testDf

UserId  MovieId  Interaction
0          604      444            1
1         4908    10378            1
2         6086      865            1
3         1424     4067            0
4         6893     1406            1
...        ...      ...          ...
166689    5750     1053            1
166690    5146    18003            0
166691    9484     9793            1
166692    2433      491            1
166693    6769    15255            0

[166694 rows x 3 columns]

In [15]:
#creating a user array for test input 
testUser = testDf[['UserId']].values.astype(np.int32)
testUser = testUser.reshape((testUser.shape[0]))
testUser

array([ 604, 4908, 6086, ..., 9484, 2433, 6769])

In [16]:
#creating a movie array for test input 
testMovie = testDf[['MovieId']].values.astype(np.int32)
testMovie = testMovie.reshape((testMovie.shape[0]))
testMovie

array([  444, 10378,   865, ...,  9793,   491, 15255])

In [17]:
#creating an array for test input 
testX = [testUser, testMovie]
testX

[array([ 604, 4908, 6086, ..., 9484, 2433, 6769]),
 array([  444, 10378,   865, ...,  9793,   491, 15255])]

In [18]:
#creating an array for test output 
testY = testDf[['Interaction']].values.astype(np.int8)
testY = testY.reshape((testY.shape[0]))
testY

array([1, 1, 1, ..., 1, 1, 0], dtype=int8)

In [19]:
#ignore warnings due to Converting sparse IndexedSlices to a dense Tensor of unknown shape warning
warnings.filterwarnings('ignore')

#Best Model For BinaryInteraction NotInteractedSample dataset loading from h5 file
#See Training2 notebook for more information
model = tf.keras.models.load_model("../Model/NotInteractedSampleModel/Model8.h5")

In [20]:
#Best Model evaluating with training values
with tf.device('/GPU:0'):
    trainingResult = model.evaluate(x = trainingX, y = trainingY, batch_size = 64, verbose = 0)

In [21]:
#Print trainingResult
trainingResult

[0.2909817301511243, 734148.0, 36244.0, 214078.0, 16666.0, 0.94715005]

In [22]:
#Best Model evaluating with validation values
with tf.device('/GPU:0'):
    validationResult = model.evaluate(x = validationX, y = validationY, batch_size = 64, verbose = 0)

In [23]:
#Print validationResult
validationResult

[0.32054571046441416, 121500.0, 6677.0, 34971.0, 3546.0, 0.93867207]

In [24]:
#Best Model evaluating with test values
with tf.device('/GPU:0'):
    testResult = model.evaluate(x = testX, y = testY, batch_size = 64, verbose = 0)

In [25]:
#Print testResult
testResult

[0.3247911827064958, 121393.0, 6833.0, 34828.0, 3640.0, 0.9371723]

In [26]:
#Creating DataFrame for data and model metrics
modelDf = pd.DataFrame(data = {'ModelData': pd.Series(['Training', 'Validation', 'Test'], dtype='str'),
                               'Negative' : pd.Series([trainingDf[trainingDf['Interaction'] == 0].shape[0], validationDf[validationDf['Interaction'] == 0].shape[0], testDf[testDf['Interaction'] == 0].shape[0]], dtype='int'),
                               'Positive' : pd.Series([trainingDf[trainingDf['Interaction'] == 1].shape[0], validationDf[validationDf['Interaction'] == 1].shape[0], testDf[testDf['Interaction'] == 1].shape[0]], dtype='int'),
                               'Loss': pd.Series([trainingResult[0], validationResult[0], testResult[0]], dtype='float'),
                               'TP': pd.Series([trainingResult[1], validationResult[1], testResult[1]], dtype='int'),
                               'FP': pd.Series([trainingResult[2], validationResult[2], testResult[2]], dtype='int'),
                               'TN': pd.Series([trainingResult[3], validationResult[3], testResult[3]], dtype='int'),
                               'FN': pd.Series([trainingResult[4], validationResult[4], testResult[4]], dtype='int'),
                               'Accuracy': pd.Series([trainingResult[5], validationResult[5], testResult[5]], dtype='float')})
modelDf

ModelData  Negative  Positive      Loss      TP     FP      TN     FN  \
0    Training    250322    750814  0.290982  734148  36244  214078  16666   
1  Validation     41648    125046  0.320546  121500   6677   34971   3546   
2        Test     41661    125033  0.324791  121393   6833   34828   3640   

   Accuracy  
0  0.947150  
1  0.938672  
2  0.937172

In [27]:
#Saving modeldf and Clearing memory
modelDf.to_pickle("../PredictData/ModelTable/NotInteractedSample.pkl")
del modelDf

In [28]:
#Best Model predicting training Interactions
with tf.device('/GPU:0'):
    predictTraining = model.predict(x = trainingX)
predictTraining

array([[0.96613497],
       [0.9742249 ],
       [0.9184351 ],
       ...,
       [0.8165405 ],
       [0.5974485 ],
       [0.98415715]], dtype=float32)

In [29]:
#Predicted Interactions appending trainingDf
trainingDf['InteractionPredict'] = predictTraining
trainingDf

UserId  MovieId  Interaction  InteractionPredict
0          5282      244            1            0.966135
1           766      213            1            0.974225
2          8209     1198            1            0.918435
3          1067     1828            1            0.996689
4          6915     1256            1            0.999579
...         ...      ...          ...                 ...
1001131   10072     1095            1            0.999562
1001132     133      396            1            0.999830
1001133    8852     6102            1            0.816540
1001134    5174     4218            0            0.597449
1001135    2711     3209            1            0.984157

[1001136 rows x 4 columns]

In [30]:
#Best Model predicting validation Interactions
with tf.device('/GPU:0'):
    predictValidation = model.predict(x = validationX)
predictValidation

array([[0.95912504],
       [0.97310954],
       [0.99597406],
       ...,
       [0.00303814],
       [0.00994752],
       [0.9051922 ]], dtype=float32)

In [31]:
#Predicted Interactions appending validaitonDf
validationDf['InteractionPredict'] = predictValidation
validationDf

UserId  MovieId  Interaction  InteractionPredict
0         8455      142            1            0.959125
1         1945      530            1            0.973110
2         7588     4030            1            0.995974
3         6186     3563            1            0.515275
4         1088     8835            1            0.963025
...        ...      ...          ...                 ...
166689    8048     1278            1            0.992861
166690    5234     4508            0            0.075500
166691    9471    19733            0            0.003038
166692    8078    15906            0            0.009948
166693    5809      337            1            0.905192

[166694 rows x 4 columns]

In [32]:
#Best Model predicting test Interactions
with tf.device('/GPU:0'):
    predictTest = model.predict(x = testX)
predictTest

array([[0.9994322 ],
       [0.46295795],
       [0.99844897],
       ...,
       [0.8129449 ],
       [0.9946484 ],
       [0.00773227]], dtype=float32)

In [33]:
#Predicted Interactions appending testDf
testDf['InteractionPredict'] = predictTest
testDf

UserId  MovieId  Interaction  InteractionPredict
0          604      444            1            0.999432
1         4908    10378            1            0.462958
2         6086      865            1            0.998449
3         1424     4067            0            0.803408
4         6893     1406            1            0.990025
...        ...      ...          ...                 ...
166689    5750     1053            1            0.999733
166690    5146    18003            0            0.004472
166691    9484     9793            1            0.812945
166692    2433      491            1            0.994648
166693    6769    15255            0            0.007732

[166694 rows x 4 columns]

In [34]:
#Dataframes merging
allDataFrame = pd.concat([trainingDf, validationDf, testDf]).reset_index(drop=True)
allDataFrame

UserId  MovieId  Interaction  InteractionPredict
0          5282      244            1            0.966135
1           766      213            1            0.974225
2          8209     1198            1            0.918435
3          1067     1828            1            0.996689
4          6915     1256            1            0.999579
...         ...      ...          ...                 ...
1334519    5750     1053            1            0.999733
1334520    5146    18003            0            0.004472
1334521    9484     9793            1            0.812945
1334522    2433      491            1            0.994648
1334523    6769    15255            0            0.007732

[1334524 rows x 4 columns]

In [35]:
#Getting all unique UserId from allDataFrame and create new Data Frame from this values
#This Data frame will used as lookup table for prediction script
userRange = range(allDataFrame['UserId'].unique().shape[0])
lookupTable = pd.DataFrame(data = {'User' : userRange})
lookupTable

User
0          0
1          1
2          2
3          3
4          4
...      ...
10068  10068
10069  10069
10070  10070
10071  10071
10072  10072

[10073 rows x 1 columns]

In [36]:
#Defined function will be checked if prediction is true
#rounding prediction returns closest label (0 or 1)
def CorrectPrediction(interaction, prediction):
    result = 0
    for i in range(len(interaction)):
        if interaction[i] == int(np.round(prediction[i])):
            result += 1
    return result

In [37]:
#Calculations for each user
calculations = np.empty(shape = (8, lookupTable.shape[0]))
for i in userRange:
    
    #Training dataframe calculations
    queryFrame = trainingDf[trainingDf['UserId'] == i]
    calculations[0][i] = queryFrame.shape[0]
    calculations[1][i] = CorrectPrediction(queryFrame['Interaction'].values, queryFrame['InteractionPredict'].values)

        
    #Validaiton dataframe calculations
    queryFrame = validationDf[validationDf['UserId'] == i]
    calculations[2][i] = queryFrame.shape[0]
    calculations[3][i] = CorrectPrediction(queryFrame['Interaction'].values, queryFrame['InteractionPredict'].values)
    
    #Test dataframe calculations
    queryFrame = testDf[testDf['UserId'] == i]
    calculations[4][i] = queryFrame.shape[0]
    calculations[5][i] = CorrectPrediction(queryFrame['Interaction'].values, queryFrame['InteractionPredict'].values)

    
    #All dataframe calculations
    #Since All dataframe contains training, validation and test dataframes
    #All dataframe results can be calculated by simply summing the training, validation and test results
    calculations[6][i] = calculations[0][i] + calculations[2][i] + calculations[4][i]
    calculations[7][i] = calculations[1][i] + calculations[3][i] + calculations[5][i]


#print
calculations

array([[ 36.,  43.,  36., ...,  54.,  48., 746.],
       [ 30.,  40.,  31., ...,  48.,  44., 733.],
       [  5.,   6.,   9., ...,   5.,   9., 126.],
       ...,
       [  2.,   5.,   8., ...,   9.,   9., 124.],
       [ 44.,  54.,  54., ...,  68.,  66., 998.],
       [ 37.,  51.,  46., ...,  61.,  61., 980.]])

In [38]:
#Calculations adding lookup table

#Training data representation count
lookupTable['TraingingRep'] = calculations[0].astype(np.int32)
#Training data Correct Predictions
lookupTable['TrainingCorrect'] = calculations[1].astype(np.int32)

#Validation data representation count
lookupTable['ValidationRep'] = calculations[2].astype(np.int32)
#validation data Correct Predictions
lookupTable['ValidationCorrect'] = calculations[3].astype(np.int32)

#Test data representation count
lookupTable['TestRep'] = calculations[4].astype(np.int32)
#test data Correct Predictions
lookupTable['TestCorrect'] = calculations[5].astype(np.int32)

#All data representation count
lookupTable['AllRep'] = calculations[6].astype(np.int32)
#all data Correct Predictions
lookupTable['AllCorrect'] = calculations[7].astype(np.int32)

lookupTable

User  TraingingRep  TrainingCorrect  ValidationRep  ValidationCorrect  \
0          0            36               30              5                  5   
1          1            43               40              6                  6   
2          2            36               31              9                  7   
3          3           574              563             97                 93   
4          4            70               67             16                 14   
...      ...           ...              ...            ...                ...   
10068  10068            43               39              6                  4   
10069  10069            38               35              7                  6   
10070  10070            54               48              5                  4   
10071  10071            48               44              9                  8   
10072  10072           746              733            126                123   

       TestRep  TestCorrect  AllRep  AllCorrect  
0            3            2      44          37  
1            5            5      54          51  
2            9            8      54          46  
3          100           97     771         753  
4           18           14     104          95  
...        ...          ...     ...         ...  
10068        0            0      49          43  
10069        7            6      52          47  
10070        9            9      68          61  
10071        9            9      66          61  
10072      126          124     998         980  

[10073 rows x 9 columns]

In [39]:
#Lookup table save as pkl file
lookupTable.to_pickle("../PredictData/LookupTable/NotInteractedSample.pkl")
del calculations
del trainingDf
del validationDf
del testDf
del allDataFrame
del lookupTable